version: 0.1.{build}
shallow_clone: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: eHv2jXP8/qllTtLERVbGMC0UDJfoJL8phvjDOMaX4MPJ+VaS/ifbiDGozzvPAIPj
  skip_symbols: true
  artifact: /.*\.nupkg/